'use client';

import { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { trainingApi } from '@/lib/api/training';
import type { Meeting } from '@/types/models';
import { cn, formatDate } from '@/lib/utils/formatters';
import { Plus, Video, CalendarBlank, Users, Clock } from '@phosphor-icons/react';
import { toast } from 'sonner';
import EmptyState from '@/components/shared/EmptyState';
import ErrorState from '@/components/shared/ErrorState';
import { SkeletonCard } from '@/components/shared/SkeletonCard';

const schema = z.object({
  title: z.string().min(2, 'Title required'),
  scheduledAt: z.string().min(1, 'Date/time required'),
  duration: z.number().min(15).max(240),
  // TODO: invitees multi-select and document attachment wired to backend
});
type FormData = z.infer<typeof schema>;

function inputCls(err?: boolean) {
  return cn(
    'w-full px-3 py-2.5 text-sm rounded-[var(--radius)] border bg-white text-slate-900 placeholder:text-slate-400',
    'focus:outline-none focus:ring-2 focus:ring-indigo-500',
    err ? 'border-rose-400' : 'border-slate-200 hover:border-slate-300'
  );
}

export default function AdminTrainingPage() {
  const [meetings, setMeetings] = useState<Meeting[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showForm, setShowForm] = useState(false);

  const { register, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm<FormData>({
    resolver: zodResolver(schema),
    defaultValues: { duration: 60 },
  });

  const load = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await trainingApi.getMyMeetings();
      setMeetings(data);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to load meetings');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, []);

  const onSubmit = async (data: FormData) => {
    const fd = new FormData();
    fd.append('title', data.title);
    fd.append('scheduledAt', data.scheduledAt);
    fd.append('duration', String(data.duration));
    // TODO: append invitees and document file
    try {
      await trainingApi.scheduleMeeting(fd);
      toast.success('Meeting scheduled! Zoom link will be generated by backend.');
      reset();
      setShowForm(false);
      load();
    } catch (err: unknown) {
      toast.error(err instanceof Error ? err.message : 'Failed to schedule meeting');
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <h1 className="text-xl font-bold text-slate-900">Training &amp; Meetings</h1>
          <p className="text-sm text-slate-500 mt-0.5">Schedule Zoom video calls and view your meeting calendar</p>
        </div>
        <button
          id="schedule-meeting-btn"
          onClick={() => setShowForm(v => !v)}
          className="flex items-center gap-2 px-4 py-2.5 rounded-[var(--radius)] text-sm font-medium bg-indigo-600 text-white hover:bg-indigo-700 btn-press"
        >
          <Plus size={16} weight="bold" />
          Schedule Meeting
        </button>
      </div>

      {/* Schedule form */}
      {showForm && (
        <div className="card p-6">
          <h2 className="font-semibold text-slate-900 mb-4">New Meeting</h2>
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
            <div>
              <label className="block text-xs font-medium text-slate-700 mb-1.5">Title <span className="text-rose-500">*</span></label>
              <input {...register('title')} placeholder="e.g. Q3 Fellow Review Meeting" className={inputCls(!!errors.title)} />
              {errors.title && <p className="mt-1 text-xs text-rose-600">{errors.title.message}</p>}
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-medium text-slate-700 mb-1.5">Date &amp; Time <span className="text-rose-500">*</span></label>
                <input type="datetime-local" {...register('scheduledAt')} className={inputCls(!!errors.scheduledAt)} />
              </div>
              <div>
                <label className="block text-xs font-medium text-slate-700 mb-1.5">Duration (minutes)</label>
                <input type="number" {...register('duration', { valueAsNumber: true })} className={inputCls()} min={15} max={240} />
              </div>
            </div>
            {/* TODO: Invitees multi-select and document attachment */}
            <div className="bg-amber-50 border border-amber-200 rounded-[var(--radius)] px-4 py-3 text-xs text-amber-700">
              <strong>Note:</strong> Invitee selection and document attachment require backend integration with the user API. Zoom meeting creation is handled server-side.
            </div>
            <div className="flex gap-3">
              <button type="button" onClick={() => setShowForm(false)} className="flex-1 py-2.5 rounded-[var(--radius)] text-sm font-medium border border-slate-200 text-slate-700">Cancel</button>
              <button type="submit" disabled={isSubmitting} className="flex-1 flex items-center justify-center gap-2 py-2.5 rounded-[var(--radius)] text-sm font-medium bg-indigo-600 text-white hover:bg-indigo-700 btn-press disabled:opacity-60">
                {isSubmitting && <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />}
                Schedule
              </button>
            </div>
          </form>
        </div>
      )}

      {/* Meetings list */}
      {loading ? (
        <div className="grid sm:grid-cols-2 gap-4">
          {[1, 2].map(i => <SkeletonCard key={i} />)}
        </div>
      ) : error ? (
        <ErrorState message={error} onRetry={load} />
      ) : !meetings.length ? (
        <div className="card">
          <EmptyState icon={Video} title="No meetings scheduled" description="Schedule a Zoom video call to get started. Invited users will receive notifications." />
        </div>
      ) : (
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {meetings.map(m => (
            <div key={m.id} className="card card-hover p-4">
              <div className="flex items-start gap-3">
                <div className="w-10 h-10 rounded-xl bg-indigo-50 flex items-center justify-center shrink-0">
                  <Video size={20} className="text-indigo-600" weight="fill" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="font-medium text-slate-900 text-sm truncate">{m.title}</div>
                  <div className="flex items-center gap-3 mt-1.5 text-xs text-slate-400 flex-wrap">
                    <span className="flex items-center gap-1"><CalendarBlank size={12} />{formatDate(m.scheduledAt, 'dd MMM, hh:mm a')}</span>
                    <span className="flex items-center gap-1"><Clock size={12} />{m.duration}min</span>
                    <span className="flex items-center gap-1"><Users size={12} />{m.invitees.length} invitees</span>
                  </div>
                </div>
              </div>
              {m.zoomJoinUrl && (
                <a
                  href={m.zoomJoinUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="mt-3 w-full flex items-center justify-center gap-2 py-2 rounded-[var(--radius-sm)] text-xs font-medium bg-indigo-600 text-white hover:bg-indigo-700 btn-press"
                >
                  <Video size={14} weight="fill" />
                  Join Meeting
                </a>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
